### ISSUE TITLE
On a fresh ubuntu install, "make test" fails with errors of missing docker-compose

### ISSUE THREAD

**Issue by skobza** [PANTHEONtech/StoneWork#5]
Add a list of required packages to documentation?

**Comment by mhalaj1** [comment]
It seems that the list of required packages, including docker-compose, already is in the top-level readme: https://github.com/PANTHEONtech/StoneWork/blob/main/README.md?plain=1#L155
Is that enough or should it be mentioned also at some other place?

**Comment by pemoticak** [comment]
Closing as Docker dependency is documented in the README.md
